import anthropic
import os
from dotenv import load_dotenv

load_dotenv()

client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))


def generate_claim_letter(
    doc_fields: dict,
    contradiction_report: dict,
    institution: str,
    circular: str,
    missing_docs: list,
) -> str:
    """Call Claude API to generate a formal claim letter."""

    # Build a summary of extracted info
    doc_summary = ""
    for fname, fields in doc_fields.items():
        doc_summary += f"\nDocument: {fname}\n"
        doc_summary += f"  Names found: {', '.join(fields.get('names', ['Not detected']))}\n"
        doc_summary += f"  Dates found: {', '.join(fields.get('dates', ['Not detected']))}\n"
        doc_summary += f"  Aadhaar: {', '.join(fields.get('aadhaar', ['Not found']))}\n"
        doc_summary += f"  PAN: {', '.join(fields.get('pan', ['Not found']))}\n"

    mismatch_summary = ""
    for comp in contradiction_report.get("comparisons", []):
        if comp["status"] != "OK":
            mismatch_summary += (
                f"  - '{comp['name1']}' ({comp['doc1']}) vs "
                f"'{comp['name2']}' ({comp['doc2']}) — "
                f"Similarity: {comp['score']}% — {comp['status']}\n"
            )

    if not mismatch_summary:
        mismatch_summary = "  No critical mismatches detected.\n"

    missing_summary = (
        "\n".join(f"  - {d}" for d in missing_docs)
        if missing_docs
        else "  All required documents appear to be present."
    )

    prompt = f"""You are a legal document specialist for India. Write a formal covering letter for a deceased person's asset claim.

Institution: {institution}
Regulatory Reference: {circular}

Extracted Document Data:
{doc_summary}

Name Mismatches Detected:
{mismatch_summary}

Missing Documents:
{missing_summary}

Write a formal, professional covering letter in English that:
1. Addresses the {institution} branch manager
2. States the purpose of the claim clearly
3. Lists all submitted documents
4. Explicitly mentions each name mismatch found and suggests the remedy (affidavit / gazette notification)
5. Cites the exact regulatory circular: {circular}
6. Notes any missing documents and explains how the family will provide them
7. Ends with a polite request for timely processing

Keep the tone formal and compassionate. Use standard Indian legal letter format with To, Subject, Salutation, Body paragraphs, and closing."""

    message = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1500,
        messages=[{"role": "user", "content": prompt}],
    )

    return message.content[0].text


def generate_whatsapp_summary(contradiction_report: dict, institution: str, missing_docs: list) -> str:
    """Generate a short plain-text WhatsApp-ready summary."""
    overall = contradiction_report.get("overall", "OK")
    critical = sum(1 for c in contradiction_report.get("comparisons", []) if c["status"] == "CRITICAL")
    minor = sum(1 for c in contradiction_report.get("comparisons", []) if c["status"] == "MINOR")

    lines = [
        f"📋 *DeathLedger Report — {institution}*",
        "",
        f"🔍 *Document Check:* {overall}",
        f"🔴 Critical mismatches: {critical}",
        f"🟡 Minor mismatches: {minor}",
    ]

    if missing_docs:
        lines.append(f"\n⚠️ *Missing Documents ({len(missing_docs)}):*")
        for d in missing_docs:
            lines.append(f"  • {d}")
    else:
        lines.append("\n✅ All required documents present.")

    lines += [
        "",
        "📁 Full claim packet generated by DeathLedger.",
        "Take the downloaded PDF to your bank branch.",
    ]

    return "\n".join(lines)