"use client";

import { useState } from 'react';
import Link from 'next/link';
import { motion, AnimatePresence, useScroll, useTransform } from 'framer-motion';
import { Shield, Search, ChevronRight, FileText, CheckCircle2, AlertCircle, Scale, Globe, Landmark, Clock, Bot, HelpCircle, ChevronDown, MessageSquare } from 'lucide-react';

const EXCUSES = [
  {
    id: 'succession',
    label: 'They want a Succession Certificate even though I have a nominee',
    label_hi: 'नॉमिनी होने के बावजूद उत्तराधिकार प्रमाण पत्र मांग रहे हैं',
    script: 'Under Section 45ZA of the Banking Regulation Act 1949, the bank is legally bound to release funds to the registered nominee without requiring a Succession Certificate. Kindly process the claim as per RBI Circular RBI/2025-26/95 or I will escalate to the Banking Ombudsman within 15 working days.',
    script_hi: 'बैंकिंग विनियमन अधिनियम 1949 की धारा 45ZA के तहत, बैंक पंजीकृत नॉमिनी को बिना उत्तराधिकार प्रमाण पत्र के राशि देने के लिए कानूनी रूप से बाध्य है। कृपया RBI परिपत्र RBI/2025-26/95 के अनुसार दावे को प्रोसेस करें अन्यथा मैं 15 कार्यदिवसों के भीतर बैंकिंग लोकपाल में शिकायत करूँगा।',
  },
  {
    id: 'affidavit',
    label: 'The branch is asking for an Affidavit on stamp paper',
    label_hi: 'शाखा स्टाम्प पेपर पर शपथ पत्र मांग रही है',
    script: 'RBI Master Circular DBR.No.Leg.BC.21/09.07.006/2015-16 explicitly states that banks cannot demand affidavits or surety bonds for claims below ₹15 lakh where a nominee exists. I request you to proceed per the circular and issue an acknowledgment within 3 working days.',
    script_hi: 'RBI मास्टर परिपत्र DBR.No.Leg.BC.21/09.07.006/2015-16 स्पष्ट रूप से कहता है कि जहाँ नॉमिनी हो, वहाँ ₹15 लाख से कम के दावों के लिए शपथ पत्र या जमानत नहीं मांगी जा सकती। कृपया परिपत्र के अनुसार आगे बढ़ें और 3 कार्यदिवसों में रसीद जारी करें।',
  },
  {
    id: 'mismatch',
    label: 'Branch is rejecting because of a name spelling mismatch',
    label_hi: 'नाम की स्पेलिंग अलग होने के कारण अस्वीकार कर रहे हैं',
    script: 'As per RBI guidelines, minor spelling variations in a deceased account holder\'s name across documents are not grounds for rejection, provided supporting identity proof links both spellings. My AI audit report — generated by DeathLedger — documents this mismatch and recommends the exact remedy under the applicable circular.',
    script_hi: 'RBI दिशानिर्देशों के अनुसार, दस्तावेज़ों में मृतक के नाम की छोटी वर्तनी भिन्नता अस्वीकृति का आधार नहीं है, बशर्ते कि पहचान प्रमाण दोनों नामों को जोड़े। DeathLedger द्वारा तैयार मेरी AI ऑडिट रिपोर्ट इस विसंगति को दस्तावेज़ीकृत करती है।',
  },
  {
    id: 'delay',
    label: 'They keep asking me to come back next week',
    label_hi: 'बार-बार अगले हफ्ते आने के लिए कह रहे हैं',
    script: 'Under RBI Circular RBI/2025-26/95, banks are mandated to settle death claims within 15 working days of receiving complete documentation. I submitted all documents on [date] and today marks [X] working days — I formally request settlement by end of week or I will file a complaint with the RBI Banking Ombudsman.',
    script_hi: 'RBI परिपत्र RBI/2025-26/95 के तहत, पूरे दस्तावेज़ मिलने के 15 कार्यदिवसों में दावा निपटाना अनिवार्य है। मैंने [तिथि] को सभी दस्तावेज़ जमा किए और आज [X] कार्यदिवस हो गए — मैं इस सप्ताह के अंत तक निपटान का अनुरोध करता हूँ अन्यथा RBI लोकपाल में शिकायत करूँगा।',
  },
  {
    id: 'noc',
    label: 'They want NOC from all legal heirs even though I am the sole nominee',
    label_hi: 'एकमात्र नॉमिनी होने के बावजूद सभी वारिसों से NOC मांग रहे हैं',
    script: 'Section 45ZA(2) of the Banking Regulation Act 1949 grants the nominee paramount right over all other legal heirs for the purpose of payment from the deceased\'s account. An NOC from other heirs is not a valid requirement when a registered nominee exists, as reaffirmed in RBI Master Circular 2024.',
    script_hi: 'बैंकिंग विनियमन अधिनियम 1949 की धारा 45ZA(2) के तहत, नॉमिनी को मृतक के खाते से भुगतान के लिए सभी कानूनी वारिसों पर सर्वोच्च अधिकार प्राप्त है। जहाँ पंजीकृत नॉमिनी हो, वहाँ अन्य वारिसों का NOC अनिवार्य नहीं है, जैसा कि RBI मास्टर परिपत्र 2024 में पुनः पुष्टि की गई है।',
  },
];

const LANG = {
  en: {
    hero_h1: 'Experience Claim Settlement Differently',
    hero_p: 'Introducing the DeathLedger Platform for claiming assets and settling legal documents after Death',
    hero_btn1: 'Start Free Audit',
    hero_btn2: 'Watch Demo',
    feat_h2: 'Claim Settlement Tools Built for India',
    feat_sub: 'No lawyers. No consultants. AI that knows Indian banking law.',
    branch_label: 'AI Negotiation Tool',
    branch_h2: 'What to say if the Branch Manager says...',
    branch_p: 'Pick the excuse you heard at the bank. Get a 2-sentence legal script citing exact Acts — read it directly from your phone screen.',
    par_tag: 'DEATHLEDGER PARIVARTAN',
    par_h2: 'Building a better India – one step at a time',
    par_p: 'Turning multiple bank visits and paperwork into minutes of solution.',
    footer_p: 'Built for Bharat. Zero legal fees. Zero data sold.',
  },
  hi: {
    hero_h1: 'दावा निपटान को अलग तरह से अनुभव करें',
    hero_p: 'नया DeathLedger AI ऑडिटर। नाम की गलतियाँ सेकंडों में पकड़ें।',
    hero_btn1: 'मुफ़्त ऑडिट शुरू करें',
    hero_btn2: 'डेमो देखें',
    feat_h2: 'भारत के लिए बने दावा निपटान उपकरण',
    feat_sub: 'कोई वकील नहीं। कोई सलाहकार नहीं। AI जो भारतीय बैंकिंग कानून जानती है।',
    branch_label: 'AI वार्ता उपकरण',
    branch_h2: 'शाखा प्रबंधक ने जो कहा उसका जवाब...',
    branch_p: 'वह बहाना चुनें जो बैंक में सुना। सटीक अधिनियमों का हवाला देते हुए 2-वाक्य की कानूनी स्क्रिप्ट पाएं।',
    par_tag: 'डेथलेजर परिवर्तन',
    par_h2: 'एक बेहतर भारत बनाना – एक कदम एक समय',
    par_p: 'कानूनी सशक्तिकरण से वित्तीय पुनर्प्राप्ति तक — DeathLedger यह सुनिश्चित करता है कि उचित उत्तराधिकारियों को उनका हक मिले।',
    footer_p: 'भारत के लिए बनाया गया। शून्य कानूनी शुल्क। कोई डेटा नहीं बेचा।',
  },
};

export default function HomePage() {
  const [openExcuse, setOpenExcuse] = useState<string | null>(null);
  const [isHindi, setIsHindi] = useState(false);
  const T = isHindi ? LANG.hi : LANG.en;

  const { scrollY } = useScroll();
  const parallaxBubble = useTransform(scrollY, [0, 3000], [0, 250]);
  const parallaxBg = useTransform(scrollY, [0, 3000], [0, -150]);

  return (
    <div style={{ backgroundColor: '#F8FAFC' }}>
      {/* ===== NAV ===== */}
      <nav style={{
        position: 'sticky',
        top: 0,
        zIndex: 50,
        background: '#004C8F', // HDFC Blue
        padding: '0 40px',
        height: '72px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <div style={{ background: 'white', padding: '6px', borderRadius: '4px' }}>
            <Shield size={28} color="#ED232A" strokeWidth={2} /> {/* HDFC Red */}
          </div>
          <span style={{
            fontFamily: 'var(--font-display)',
            fontSize: '24px',
            fontWeight: 800,
            color: 'white',
            letterSpacing: '0.5px',
          }}>
            DeathLedger
          </span>
        </div>

        <button
          onClick={() => setIsHindi(!isHindi)}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            background: isHindi ? '#FFC107' : 'rgba(255,255,255,0.15)',
            border: '2px solid rgba(255,255,255,0.4)',
            borderRadius: '999px',
            padding: '8px 20px',
            cursor: 'pointer',
            transition: 'all 0.3s',
          }}
        >
          <Globe size={16} color={isHindi ? '#1E293B' : 'white'} />
          <span style={{ fontSize: '14px', fontWeight: 700, color: isHindi ? '#1E293B' : 'white' }}>
            {isHindi ? 'English' : 'हिन्दी'}
          </span>
        </button>
      </nav>

      {/* ===== HERO (Screenshot 3 Style) ===== */}
      <section style={{
        position: 'relative',
        height: '550px',
        display: 'flex',
        alignItems: 'center',
        padding: '0 80px',
        overflow: 'hidden',
      }}>
        {/* Background Image */}
        <motion.div style={{
          position: 'absolute',
          inset: 0,
          background: 'url("https://images.unsplash.com/photo-1607867856297-085b093eb8e8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fG9sZCUyMHBlb3BsZSUyMGluZGlhbiUyMGltYWdlJTIwbGFuZHNjYXBlJTIwc3RyZXNzZWQlMjBleHByZXNzaW9ufGVufDB8fDB8fHww") center/cover',
          zIndex: 0,
          y: parallaxBg,
        }} />
        {/* Gradient Overlay for text readability */}
        <div style={{
          position: 'absolute',
          inset: 0,
          background: 'linear-gradient(90deg, rgba(0,0,0,0.85) 0%, rgba(0,0,0,0.4) 50%, transparent 100%)',
          zIndex: 1,
        }} />

        <motion.div
          initial={{ opacity: 0, x: -30 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6 }}
          style={{ position: 'relative', zIndex: 2, maxWidth: '600px' }}
        >
          <h1 style={{
            fontFamily: 'var(--font-display)',
            fontSize: '56px',
            fontWeight: 800,
            color: 'white',
            lineHeight: 1.1,
            marginBottom: '16px',
          }}>
            {T.hero_h1}
          </h1>
          <p style={{
            fontSize: '18px',
            color: 'rgba(255,255,255,0.9)',
            marginBottom: '32px',
            fontWeight: 500,
            lineHeight: 1.5,
          }}>
            {T.hero_p}
          </p>
          <div style={{ display: 'flex', gap: '16px' }}>
            <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
              <Link href="/audit" style={{
                background: 'white',
                color: '#004C8F',
                textDecoration: 'none',
                padding: '16px 36px',
                borderRadius: '16px',
                fontWeight: 800,
                fontSize: '17px',
                display: 'flex',
                alignItems: 'center',
                gap: '10px',
                boxShadow: '0 8px 32px rgba(0, 76, 143, 0.4)',
                transition: 'all 0.3s ease'
              }}>
                {T.hero_btn1} <ChevronRight size={18} strokeWidth={2.5} color="#ED232A" />
              </Link>
            </motion.div>
          </div>
        </motion.div>

      </section>

      {/* ===== BANKING SOLUTIONS / FEATURES (Screenshot 1 Style) ===== */}
      <section style={{ padding: '120px 40px', background: '#F8FAFC', textAlign: 'center' }}>
        <div style={{ marginBottom: '12px', fontSize: '13px', fontWeight: 700, color: '#004C8F', letterSpacing: '1.5px', textTransform: 'uppercase' }}>WHY DEATHLEDGER</div>
        <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '36px', color: '#1E293B', marginBottom: '8px', fontWeight: 700 }}>
          {T.feat_h2}
        </h2>
        <p style={{ fontSize: '16px', color: '#64748B', marginBottom: '48px' }}>{T.feat_sub}</p>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '24px', maxWidth: '1200px', margin: '0 auto' }}>
          {[
            { title: 'Smart Name Matching', desc: 'Detects "Rajesh Kumar" vs "R. Kumar" automatically.', icon: <Search size={32} color="#004C8F" /> },
            { title: 'RBI 2026 Compliant', desc: 'Cites exact circular RBI/2025-26/95 in every letter.', icon: <Scale size={32} color="#004C8F" /> },
            { title: 'One-Click Packet', desc: 'Download a court-ready PDF with checklist & report.', icon: <FileText size={32} color="#004C8F" /> },
            { title: 'Hindi Interface', desc: 'Full UI switch for Tier 2 & 3 families.', icon: <Globe size={32} color="#004C8F" /> },
            { title: 'Institution-Specific', desc: 'Separate checklists for SBI, LIC, HDFC, and ICICI.', icon: <Landmark size={32} color="#004C8F" /> },
            { title: '15-Day SLA Tracker', desc: 'Know exactly when the bank is legally obligated to pay.', icon: <Clock size={32} color="#004C8F" /> },
          ].map((feat, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: false, amount: 0.1 }}
              transition={{ delay: i * 0.1 }}
              whileHover={{ y: -4, boxShadow: '0 16px 40px rgba(0, 76, 143, 0.08)' }}
              style={{
                background: 'white',
                borderRadius: '16px',
                padding: '24px 36px',
                textAlign: 'center',
                boxShadow: '0 4px 20px rgba(0,0,0,0.03)',
                border: '1px solid #e5e7eb',
                transition: 'all 0.3s ease',
              }}
            >
              <div style={{ marginBottom: '16px', display: 'flex', justifyContent: 'center' }}>
                <div style={{ background: 'rgba(0, 76, 143, 0.1)', padding: '16px', borderRadius: '50%' }}>
                  {feat.icon}
                </div>
              </div>
              <h3 style={{ fontSize: '19px', fontWeight: 800, color: '#1E293B', marginBottom: '8px' }}>{feat.title}</h3>
              <p style={{ fontSize: '14px', color: '#64748B', lineHeight: 1.4 }}>{feat.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ===== BRANCH MANAGER PUSH-BACK SCRIPT ===== */}
      <section style={{
        background: '#FFC107',
        padding: '120px 40px',
        position: 'relative',
        overflow: 'hidden',
      }}>
        {/* Decorative question mark graphic */}
        <div style={{
          position: 'absolute',
          right: '4%',
          top: '50%',
          transform: 'translateY(-50%)',
          zIndex: 0,
        }}>
          <motion.div style={{ y: parallaxBubble }}>
            <motion.div
              animate={{ 
                y: [-10, 10, -10],
                boxShadow: [
                  '0 4px 20px rgba(255, 215, 0, 0.15)',
                  '0 0 60px rgba(255, 215, 0, 0.6)',
                  '0 4px 20px rgba(255, 215, 0, 0.15)'
                ]
              }}
              transition={{
                duration: 6,
                ease: "easeInOut",
                repeat: Infinity,
              }}
              style={{
                width: '320px',
                height: '320px',
                background: 'rgba(255,255,255,0.25)',
                borderRadius: '50%',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                backdropFilter: 'blur(12px)',
                border: '1px solid rgba(255,255,255,0.6)',
              }}
            >
              <HelpCircle size={160} color="rgba(0,76,143,0.3)" strokeWidth={1.2} />
            </motion.div>
          </motion.div>
        </div>

        <div style={{ maxWidth: '1100px', margin: '0 auto', position: 'relative', zIndex: 1 }}>
          {/* Header */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '12px' }}>
            <MessageSquare size={28} color="#1E293B" strokeWidth={2} />
            <span style={{ fontSize: '13px', fontWeight: 800, color: '#1E293B', letterSpacing: '1.5px', textTransform: 'uppercase' }}>{T.branch_label}</span>
          </div>
          <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '42px', color: '#1E293B', marginBottom: '12px', fontWeight: 800, maxWidth: '560px', lineHeight: 1.1 }}>
            {T.branch_h2}
          </h2>
          <p style={{ fontSize: '16px', color: '#374151', marginBottom: '40px', maxWidth: '520px', lineHeight: 1.6, fontWeight: 500 }}>
            {T.branch_p}
          </p>

          {/* Accordion Excuses */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', maxWidth: '680px' }}>
            {EXCUSES.map((excuse, i) => (
              <motion.div
                key={excuse.id}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: false, amount: 0.1 }}
                transition={{ delay: i * 0.07 }}
                style={{ borderRadius: '12px', overflow: 'hidden', boxShadow: '0 4px 16px rgba(0,0,0,0.08)' }}
              >
                {/* Toggle Header */}
                <button
                  onClick={() => setOpenExcuse(openExcuse === excuse.id ? null : excuse.id)}
                  style={{
                    width: '100%',
                    background: openExcuse === excuse.id ? '#004C8F' : 'white',
                    border: 'none',
                    padding: '24px 32px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    cursor: 'pointer',
                    textAlign: 'left',
                    transition: 'background 0.25s',
                  }}
                >
                  <span style={{
                    fontSize: '15px',
                    fontWeight: 600,
                    color: openExcuse === excuse.id ? 'white' : '#1E293B',
                    lineHeight: 1.4,
                    paddingRight: '16px',
                  }}>
                    &ldquo;{isHindi ? excuse.label_hi : excuse.label}&rdquo;
                  </span>
                  <ChevronDown
                    size={20}
                    color={openExcuse === excuse.id ? 'white' : '#004C8F'}
                    style={{
                      flexShrink: 0,
                      transform: openExcuse === excuse.id ? 'rotate(180deg)' : 'rotate(0deg)',
                      transition: 'transform 0.25s',
                    }}
                  />
                </button>

                {/* Script Panel */}
                <AnimatePresence initial={false}>
                  {openExcuse === excuse.id && (
                    <motion.div
                      key="panel"
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.28 }}
                      style={{ overflow: 'hidden', background: '#EFF6FF' }}
                    >
                      <div style={{ padding: '20px' }}>
                        <p style={{ fontSize: '12px', fontWeight: 800, color: '#004C8F', letterSpacing: '1px', marginBottom: '10px', textTransform: 'uppercase' }}>
                          📋 {isHindi ? 'आपकी कानूनी स्क्रिप्ट — इसे ज़ोर से पढ़ें' : 'Your Legal Script — Read This Aloud'}
                        </p>
                        <p style={{
                          fontSize: '15px',
                          color: '#1E293B',
                          lineHeight: 1.7,
                          fontWeight: 500,
                          background: 'white',
                          padding: '16px 20px',
                          borderRadius: '8px',
                          borderLeft: '4px solid #ED232A',
                          boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
                        }}>
                          {isHindi ? excuse.script_hi : excuse.script}
                        </p>
                        <p style={{ fontSize: '12px', color: '#64748B', marginTop: '10px', fontStyle: 'italic' }}>
                          ⚖️ Cites Banking Regulation Act 1949 · RBI/2025-26/95
                        </p>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ===== PARIVARTAN STYLE / IMPACT BANNER (Screenshot 4 Style) ===== */}
      <section style={{
        position: 'relative',
        padding: '120px 40px',
        display: 'flex',
        alignItems: 'center',
        background: '#E6EEF8',
        overflow: 'hidden',
      }}>
        {/* Background Image on Left */}
        <div style={{
          position: 'absolute',
          left: 0,
          top: 0,
          bottom: 0,
          width: '50%',
          background: 'url("https://images.unsplash.com/photo-1686061593213-98dad7c599b9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8c29tZSUyMGZpbmFuY2UlMjBhbmFseXRpY3MlMjBpbWFnZXxlbnwwfHwwfHx8MA%3D%3D") center/cover',
          zIndex: 0,
        }} />
        {/* Gradient Blend */}
        <div style={{
          position: 'absolute',
          left: '40%',
          top: 0,
          bottom: 0,
          width: '20%',
          background: 'linear-gradient(90deg, transparent, #E6EEF8)',
          zIndex: 1,
        }} />

        <div style={{ maxWidth: '1200px', margin: '0 auto', width: '100%', display: 'flex', justifyContent: 'flex-end', position: 'relative', zIndex: 2 }}>
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: false, amount: 0.2 }}
            style={{ width: '50%', paddingLeft: '40px' }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px' }}>
              <div style={{ background: 'white', padding: '4px', borderRadius: '4px' }}><Shield size={20} color="#ED232A" /></div>
              <span style={{ fontSize: '18px', fontWeight: 800, color: '#004C8F', letterSpacing: '0.5px' }}>{T.par_tag}</span>
            </div>

            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '42px', color: '#1E293B', marginBottom: '20px', fontWeight: 800, lineHeight: 1.1 }}>
              {T.par_h2}
            </h2>
            <p style={{ fontSize: '16px', color: '#475569', marginBottom: '32px', lineHeight: 1.6 }}>
              {T.par_p}
            </p>

            {/* Problem Statement Metrics */}
            <div style={{ marginBottom: '12px', fontSize: '11px', fontWeight: 800, color: '#ED232A', letterSpacing: '1.5px', textTransform: 'uppercase' }}>THE PROBLEM IN NUMBERS</div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px', marginBottom: '32px' }}>
              {[
                { number: '₹65,000 Cr', label: 'Unclaimed assets in Indian banks', color: '#ED232A' },
                { number: '2.3 Cr', label: 'Death claims filed yearly', color: '#004C8F' },
                { number: '14–36 mo', label: 'Average settlement time', color: '#ED232A' },
                { number: '₹50,000+', label: 'Avg legal fees per family', color: '#004C8F' },
              ].map((stat, i) => (
                <motion.div
                  key={i}
                  whileHover={{ y: -4, boxShadow: '0 12px 32px rgba(0,0,0,0.08)' }}
                  style={{
                    background: 'white',
                    padding: '24px',
                    borderRadius: '16px',
                    boxShadow: '0 4px 16px rgba(0,0,0,0.04)',
                    borderLeft: `4px solid ${stat.color}`,
                    transition: 'all 0.3s ease'
                  }}>
                  <div style={{ fontSize: '28px', fontWeight: 800, color: stat.color, marginBottom: '6px' }}>{stat.number}</div>
                  <div style={{ fontSize: '14px', color: '#64748B', fontWeight: 500 }}>{stat.label}</div>
                </motion.div>
              ))}
            </div>

          </motion.div>
        </div>
      </section>

      {/* ===== FOOTER ===== */}
      <footer style={{
        background: '#003366',
        padding: '40px',
        textAlign: 'center',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px', marginBottom: '12px' }}>
          <Shield size={24} color="white" />
          <span style={{
            fontFamily: 'var(--font-display)',
            fontSize: '24px',
            color: 'white',
            fontWeight: 800,
          }}>
            DeathLedger
          </span>
        </div>
        <p style={{ color: '#94A3B8', fontSize: '14px', marginBottom: '8px' }}>
          {T.footer_p}
        </p>
      </footer>
    </div>
  );
}
