// WhatsApp-formatted summary generator

import { AuditResult } from './demoData';

export function generateWhatsAppSummary(audit: AuditResult): string {
  const statusEmoji =
    audit.summary.overallStatus === 'CRITICAL'
      ? '🔴'
      : audit.summary.overallStatus === 'MINOR'
      ? '🟡'
      : '✅';

  const criticalLines = audit.comparisons
    .filter((c) => c.severity === 'CRITICAL')
    .map((c) => `❌ ${c.docA} says "${c.nameA}" but ${c.docB} says "${c.nameB}"`)
    .join('\n');

  const missingLines = audit.missingDocuments
    .map((d) => `📋 Missing: ${d}`)
    .join('\n');

  const simplifiedNote = audit.regulatory.simplifiedProcedure
    ? `\n✅ Simplified Procedure applies (claim < ₹15L) — cite RBI/2025-26/95`
    : '';

  const nomineeNote = audit.regulatory.nomineeProtection
    ? `\n🛡️ NOMINEE EXISTS: Bank cannot demand Succession Certificate (Sec 45ZA)`
    : '';

  return `🔍 *DeathLedger Audit Report*
━━━━━━━━━━━━━━━━
👤 Claimant: ${audit.claimant.name}
🏦 Institution: ${audit.institution}
${statusEmoji} Result: ${audit.summary.criticalCount} Critical | ${audit.summary.minorCount} Minor | ${audit.summary.okCount} OK

${criticalLines || '✅ No name mismatches found'}

${missingLines || '✅ All required documents present'}${simplifiedNote}${nomineeNote}

⏰ Bank must settle within *15 days* of complete docs
⚖️ Cite: RBI/2025-26/95 (Oct 2025 Directions)

_Generated by DeathLedger — Zero legal fees_`;
}
